workspace = { members = ["project_3"] }
[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]

reqwest = { version = "0.11", features = ["blocking"] }
aes = "0.8.2"
block-modes = "0.9.1"
